### ISSUE TITLE
Volume input elements in UI show System.InvalidCastException initially

### ISSUE THREAD

**Issue by AnonymerNiklasistanonym** [Ganom/SimpleTwitchEmoteSounds#1]
![xdx](https://github.com/user-attachments/assets/39698c3d-b634-4938-bec7-15f88c6b3a9e)

The functionality of the application does not appear to be impaired since:

- The preview sound button works anyways
- Touching the input and changing it to any value removes the error + the set volume value is used

I'm not sure why it only happens on my Windows 11 Laptop (`dotnet --version` returns 8.0.402) since I would assume it doesn't happen on the dev machine, but I could solve it in two ways:

1. Update the file `Models/SoundCommand.cs` to use `0,5` instead of the current `0.5`:
  
  ```cs
  //[ObservableProperty] private string _volume = "0.5";
  [ObservableProperty] private string _volume = "0,5";
  ```

  Since the volume number is stored as a string and expected to have a `,` for some reason.

2. Use actual numbers to prevent such casting bugs in the first place:
  
  ```cs
  //[ObservableProperty] private string _volume = "0.5";
  [ObservableProperty] private float _volume = 0.5f;
  ```

   I'm not sure for the reason of using strings instead of numbers but it seems to work so this solution which would also break existing installations is not necessary but seems logical.

   > [!WARNING]
   > Solution 2 will make the program crash if there is an existing `Settings/sounds.json` file which mismatches the volume data type (expected number -> found string) which means it either has to be manually deleted or manually updated for the program to not crash any more.
   > (But I migrated all numbers to floats in my fork and the program seems to work fine with this change)

Disclaimer: I have not programmed a single C# thing in my life, so I have no deep understanding of the code. But I like the program a lot, thx for sharing it.

**Comment by Ganom** [comment]
This is a very interesting issue, I originally had it as a float as a clean binding is nicer, but input fields like TextBox and NumericUpDown return a value of `string.empty` if you have an empty field which causes a casting error like shown above.

For me, solution 1 actually introduces the issue for me rather than fixing it. 

![image](https://github.com/user-attachments/assets/004a172e-69ec-47c4-94e6-78f9b26471fd)

I'm unable to reproduce the issue with standard configuration.

**Comment by AnonymerNiklasistanonym** [comment]
I'm gonna assume your (Windows) region is `English (America)` or another region that uses `,` to separate decimals while my PCs region (`German (Germany)`) generally uses `.` to do this.
I tested this on my Laptop just now and can at least confirm that this will make my initial error disappear on an application restart after changing the Windows `Regional Format` in the Windows settings under `Time & language > Language & region`.
So I guess the conversion of the input value (float) to the string is a (region) localized conversion instead of a standardized one.

**Comment by Ganom** [comment]
That makes sense. I think the simplest solution here would be just changing the default value to 1 as that would remove any culture variance.

**Comment by AnonymerNiklasistanonym** [comment]
Just in case you wanna try it out I played with the code for a sec around if it would be possible to not have casting errors on empty inputs and found some `OnFooChanged(value)` listener in the code and just added that to the numbers (932bf5dacf264c59f4427b9acec5bb43cf1927f7, 88864667781b43e02504cc36cecd5becb08e2015).

```cs
//[ObservableProperty] private string _volume = "0.5";
[ObservableProperty] private float? _volume = 0.5f;

partial void OnVolumeChanged(float? value)
    {
        if (value == null)
        {
            Volume = 0.5f;
        }
    }
```

This results in a probably ugly UI for the number inputs but defaults on empty to the default values while syncing the sliders too:

![xbx](https://github.com/user-attachments/assets/913ac29c-795e-44e3-802a-eddf6ff53c89)

And the `Settings/sounds.json` seems to just use the default values too:

```json
{
  "SoundCommands": [
    {
      "Name": "gun sol",
      "Category": "7tv",
      "SoundFiles": [
        {
          "FileName": "plink.mp3",
          "FilePath": "...\\SimpleTwitchEmoteSounds\\example\\plink.mp3",
          "Percentage": 1
        }
      ],
      "Enabled": true,
      "IsExpanded": true,
      "PlayChance": 1,
      "SelectedMatchType": 1,
      "Volume": 0.5
    }
  ]
}
```

EDIT: To have my fork version with Linux support (my machine, don't want to force you to support it so I just forked it)  work with the normal version of the program I wrote a quick and dirty migration path when loading in the numbers as strings `AppSettings` config. [02b2332d90baf15fa403a514c442b82681192c9d, 53202a8948d751f1cc77260b90d57d4fb1378f9b]

If you want to implement/try this migration which wouldn't break existing configurations as far as I can tell I could make a pull request otherwise sorry for being annoying ^^
